### PR TITLE
Allow searching for multiple runs.

### PR DESCRIPTION
**Pull request by nerdstrike**
Crude... Had difficulty disabling the alternate search mode when it doesn't make any sense.

### CODE REVIEW

**Comment by mgcam** [comment]
The order the runs are displayed in in the table is rundom. It does not correspond to the order of listing the run in the heading, neither it is alphabetical. Better usability if the rows are appended to the table.

**Comment by mgcam** [comment]
Searching for a run that does not exist. Example - ui/run/TRACTION-RUN-505/TRACTION-RUN-565/TRACTION-RUN-9999, the last run does not exist.

- The error message flashes very quickly - increase duration it is displayed. 
- Consider what table title is appropriate in this case. Currently it's 'Wells for run TRACTION-RUN-505,TRACTION-RUN-565,TRACTION-RUN-9999'

**Comment by mgcam** [comment]
The down arrow on the 'Search' button is very faint, gives no hint about an alternative action. Is it possible to add a tool-tip?

**Review by mgcam — CHANGES_REQUESTED** [review]
Please see general comments

**Comment by mgcam** [comment]
Adding a run (also) to a display with no previous run chosen (the home-style display) results in an unhandled JavaScript error - TypeError: s.params.runName is undefined. No useful feedback to the user. Have to either display an error (Can only add to an existing run selection) or reinterpret the request as a search.

**Comment by nerdstrike** [comment]
I tried the `disabled` attribute for the `el-select` options, but it really didn't work the way I hoped it would. I'll try to catch the fault

**Comment by nerdstrike** [comment]
Got it to grey out the option unless we're already in a state which must have another run set.

**Review by mgcam — APPROVED** [review]

**Pull request merged**
